version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "indoor-iot-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1rs00glapaxi1"
s3_prefix = "indoor-iot-backend"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "APIName=\"indoor_iot\""
image_repositories = []
