AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  indoor-iot-backend
  SAM Template for indoor-iot-backend

Parameters:
  APIName:
    Type: String
    Description: "Name of the API, for generate names for resources"
    MinLength: 3
    MaxLength: 20
    AllowedPattern: '^[a-zA-Z][a-zA-Z0-9_]*$'

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  LocalizationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: LocalizationFunction
      Handler: localization.App::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        DynamoDBEvent:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt IntermediateLocationsQueue.StreamArn
            BatchSize: 10
            StartingPosition: TRIM_HORIZON

  IntermediateLocationsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: IntermediateLocationsFunction
      Handler: intermediatelocations.App::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        DynamoDBEvent:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt TagsHistoricalTable.StreamArn
            BatchSize: 10
            StartingPosition: TRIM_HORIZON

  TagsHistoricalTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: epc
          AttributeType: S
      KeySchema: 
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: epc
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_IMAGE
        
  UpdaterHistoricalTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema: 
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  IntermediateLocationsQueue:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: epc
          AttributeType: S
      KeySchema: 
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: epc
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  LocalizedTagsTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: epc
          AttributeType: S    
      KeySchema: 
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: epc
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  
  TagsHistoricalDBRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${APIName}-tags-historical-role
      ManagedPolicyArns:
        - Ref: AppSyncDynamoDBPolicy
      AssumeRolePolicyDocument:
        Version: 2022-1-14
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - appsync.amazonaws.com
    DependsOn:
      -   TagsHistoricalDBPolicy

  TagsHistoricalDBPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Managed policy to allow AWS AppSync to access the tables created by this template.
      Path: /tags_historical/
      PolicyDocument:
        Version: 2022-1-14
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:DeleteItem
              - dynamodb:UpdateItem
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
            Resource: !Join [ "", [!GetAtt TagsHistoricalTable.Arn, "*"]]
  
  TagsHistoricalApi:
    Type: "AWS::AppSync::GraphQLApi"
    Description: "The GraphQL API for sending historical tag measurements"
    Properties:
      AuthenticationType: "AMAZON_COGNITO_USER_POOLS"
      Name: !Sub ${APIName}-tags-historical-api
      UserPoolConfig:
        UserPoolId: !Ref UserPoolClient
        AwsRegion: !Sub ${AWS::Region}
        DefaultAction: "ALLOW"

  TagsHistoricalSchema:
    Type: "AWS::AppSync::GraphQLSchema"
    Properties:
      ApiId: !GetAtt TagsHistoricalApi.ApiId
      Definition: |
        type Measurement {
          id: ID!
          epc: String!
          user_id: String!
          area_id: Int!
          channel_estimates: [Complex]
          timestamp: String!
        }

        type Complex {
          measurement_id: ID!
          real: Float!
          imaginary: Float!
        }

        type Query {
          getAreaMeasurements(area_id: Int!): [Measurement]
          getTimedMeasurements(user_id: String!, timestamp: String!): [Measurement]
        }

        type Mutation {
          addMeasurement(id: ID!,
            epc: String!,
            timestamp: String!,
            user_id: String!,
            area_id: Int!): Measurement

          addComplex(measurement_id: ID!,
            real: Float!
            imaginary: Float!): Comment

        }

        type Schema {
          query: Query
          mutation: Mutation
        }

  TagsHistoricalDataSource:
    Type: "AWS::AppSync::DataSource"
    Properties:
      ApiId: !GetAtt TagsHistoricalApi.ApiId
      Name: !Sub ${APIName}_tags_historical_table
      Description: "The historical tag Table AppSync Data Source"
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt TagsHistoricalDBRole.Arn
      DynamoDBConfig:
        TableName: !Ref TagsHistoricalTable
        AwsRegion: !Sub ${AWS::Region}

  




Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
