version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::477318148124:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-CX67BAZAWC7Z"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::477318148124:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-1R2CITHVW1W8S"
cloudformation_execution_role = "arn:aws:iam::477318148124:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-159XFYEOPXBEL"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-1hrfkso36armz"
image_repository = ""
region = "us-east-2"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::477318148124:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-1IETGJTL5O0MO"
cloudformation_execution_role = "arn:aws:iam::477318148124:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-1BZEFO7AJZW7V"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-1jpgwk8g19iu3"
image_repository = ""
region = "us-east-2"
